### PR TITLE
Multimedia

### PR DESCRIPTION
**Pull request by tzohpilotl**
Since I wasn't shure I left my commits as they were, without squashing or anything.

### CODE REVIEW

**Comment by ulisesac4** [comment]
Can you explain me what is the function of the member pano?, because that is doing some conflicts between master and your branch

**Comment by aldompe95** [comment]
Seems ready to merge

**Comment by ulisesac4** [comment]
Aza, does the map render ok in your branch?, i had to use normal px in height to make it work, if not when this branch is merged map rendering is gonna be broken.

**Comment by tzohpilotl** [comment]
@UlisesAC4 Yes it renders fine. Do you mean the 'pano' `div`? It is where the street view is rendered, it is passed to the StreetViewPanorama's constructor.

**Comment by ulisesac4** [comment]
Can you check again your repo? I fetched 10 minutes ago and opened the site, maps are not showing, also i cannot see the pano div implemented on the index file

**Comment by tzohpilotl** [comment]
Seems like @aldompe95 fixed the conflicts, so it should be ok to merge now. The issue was that by the time I pushed this branch, yours wasn't merged already, so my local version didn't have your changes. Before this merge was approved, you merged your branch, which introduced the conflicts.

**Comment by aldompe95** [comment]
@azaroma yeah merge it :D

**Comment by aldompe95** [comment]
@azaroma it looks like there is an issue in the code apart of the conflicts already solved

**Comment by ulisesac4** [comment]
What issues, streetview not rendering right?

**Comment by tzohpilotl** [comment]
@aldompe95 What would those be? I haven't noticed them

**Comment by aldompe95** [comment]
@azaroma it was the html i delete, dont worry

**Pull request merged**
