### PR TITLE
Visual design

### PR DESCRIPTION
**Pull request by ulisesac4**
Wellll guys this it the page visual design, it is a little mainstream set of colors, but i believe it blends well.

The main concern that it has to be noted is that the map cannot use a relative height otherwise bad workarounds can disrupt all the padding of the framework, so it is better at the moment to use fixed height, that is why it change it to px on the style file.

It may be a little messy the change in the colors used in the third commit, in the end I prefer to avoid grey and black as a website base colors, that is why I ended change them at the end.

Had to "improve" a little bit the function printDistance in the geolocation.js file because the list items needed to use an specific class to change their color, the rest of the file is as it was in the main branch.

I believe that it is better to have the "Get Distance" button first because the "Ok" or "Accept" buttons are always the first to appear and, so it is better to have a "positive" action first to "maintain" consistency in UX.

Also, I do not find use to have links in the page neither a mobile menu because of course there is no need of links, anyway what do you think of this?

### CODE REVIEW

**Comment by aldompe95** [comment]
I think its ready to merge, but remember we need to use css3.
Maybe you could add some simple effects in css3 :D https://www.w3schools.com/css/css3_animations.asp

**Comment by ulisesac4** [comment]
Well I "believe" that it is really done with the framework as it is, If you want some animations I can add the next with the framework default animations:

- At the moment the page is loaded, the main content appears with a slide in animation
- Hover effect for the main content when the mouse is over the frame

What do you think about this animations?, do you like this or prefer other types of animations?

**Comment by aldompe95** [comment]
Sorry you are right about the framework, well you dont need to put animation it was just some idea i thought. youre ready to merge to me :+1:

**Comment by ulisesac4** [comment]
Ok :), so we just need to azaroma to vote to merge right?

**Comment by tzohpilotl** [comment]
Sorry guys, I missed these notifications, I agree with the merging

**Comment by ulisesac4** [comment]
Well, as everybody is fine with the merging, it is done now :)

**Pull request merged**
